# GitHub Sponsorship Configuration
# These are supported funding model platforms

# Primary sponsorship through GitHub Sponsors
github: [Vaporjawn]

# Alternative funding platforms (uncomment and configure as needed)
# patreon: # Vaporjawn
# open_collective: # travel-logger
# ko_fi: # vaporjawn
# tidelift: # npm/travel-logger
# community_bridge: # travel-logger
# liberapay: # Vaporjawn
# issuehunt: # Vaporjawn
# otechie: # Vaporjawn
# lfx_crowdfunding: # travel-logger

# Custom funding URLs (uncomment and add as needed)
# custom: ['https://www.buymeacoffee.com/vaporjawn', 'https://paypal.me/vaporjawn']

# 🌟 Thank you for supporting open source development!
# Your sponsorship helps maintain and improve Travel Logger for everyone.
#
# Sponsorship benefits:
# - Priority support for issues and questions
# - Early access to new features
# - Recognition in project documentation
# - Direct influence on roadmap priorities
# - Commercial use support
