name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees:
  - Vaporjawn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - Frontend/UI Enhancement
        - Backend/API Enhancement
        - New Map Feature
        - User Authentication
        - Data Management
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Needed for project success
        - Critical - Blocking current work
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: Explain the specific use case and how it would benefit users
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: Technical suggestions, UI mockups, or implementation approaches
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information, mockups, or examples that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to work on this feature?
      options:
        - label: I'm willing to implement this feature myself
        - label: I can provide design/UX input
        - label: I can help with testing
        - label: I can provide feedback during development

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true